export interface Airline {
  code: string;
  name: string;
}

interface Airlines {
  American: Airline[];
  Alaska: Airline[];
  Delta: Airline[];
}

const airlines: Airlines = {
  American: [
    { code: "TN", name: "Air Tahiti Nui" },
    { code: "AS", name: "Alaska Airlines" },
    { code: "AA", name: "American Airlines" },
    { code: "9K", name: "Cape Air" },
    { code: "CX", name: "Cathay Pacific" },
    { code: "EY", name: "Etihad Airways" },
    { code: "AAA", name: "American AAdvantage" },
    { code: "FJ", name: "Fiji Airways" },
    { code: "AY", name: "Finnair" },
    { code: "G3", name: "GOL Airlines" },
    { code: "HA", name: "Hawaiian Airlines" },
    { code: "IB", name: "Iberia" },
    { code: "JL", name: "Japan Airlines" },
    { code: "B6", name: "JetBlue Airways" },
    { code: "MH", name: "Malaysia Airlines" },
    { code: "QF", name: "Qantas Airways" },
    { code: "QR", name: "Qatar Airways" },
    { code: "AT", name: "Royal Air Maroc" },
    { code: "RJ", name: "Royal Jordanian" },
    { code: "BA", name: "British Airways" },
    { code: "UL", name: "SriLankan Airlines" },
  ],
  Alaska: [
    { code: "AA", name: "American Airlines" },
    { code: "AS", name: "Alaska Airlines" },
    { code: "BA", name: "British Airways" },
    { code: "CX", name: "Cathay Pacific" },
    { code: "FJ", name: "Fiji Airways" },
    { code: "AY", name: "Finnair" },
    { code: "IB", name: "Iberia" },
    { code: "JL", name: "Japan Airlines" },
    { code: "MH", name: "Malaysia Airlines" },
    { code: "AMP", name: "Alaska Milage Plan" },
    { code: "QF", name: "Qantas Airways" },
    { code: "QR", name: "Qatar Airways" },
    { code: "AT", name: "Royal Air Maroc" },
    { code: "RJ", name: "Royal Jordanian" },
    { code: "UL", name: "SriLankan Airlines" },
    { code: "EI", name: "Aer Lingus" },
    { code: "TN", name: "Air Tahiti Nui" },
    { code: "DE", name: "Condor" },
    { code: "LY", name: "EL AL Israel Airlines" },
    { code: "HU", name: "Hainan Airlines" },
    { code: "FI", name: "Icelandair" },
    { code: "KE", name: "Korean Air" },
    { code: "LA", name: "LATAM Airlines" },
    { code: "7H", name: "Ravn Alaska" },
    { code: "SQ", name: "Singapore Airlines" },
    { code: "JX", name: "STARLUX Airlines" },
  ],
  Delta: [
    { code: "DL", name: "Delta Airlines" },
    { code: "AR", name: "Aerolineas Argentinas" },
    { code: "AF", name: "Air France" },
    { code: "DLS", name: "Delta SkyMiles" },
    { code: "9K", name: "Cape Air" },
    { code: "MU", name: "China Eastern Airlines" },
    { code: "CI", name: "China Airlines" },
    { code: "CZ", name: "China Southern Airlines" },
    { code: "GA", name: "Garuda Indonesia" },
    { code: "HA", name: "Hawaiian Airlines" },
    { code: "KL", name: "KLM Royal Dutch Airlines" },
    { code: "KE", name: "Korean Air" },
    { code: "LA", name: "LATAM Airlines" },
    { code: "AZ", name: "ITA Airways" },
    { code: "AE", name: "Mandarin Airlines" },
    { code: "ME", name: "Middle East Airlines" },
    { code: "SV", name: "Saudia Airlines" },
    { code: "FM", name: "Shanghai Airlines" },
    { code: "RO", name: "Tarom" },
    { code: "VN", name: "Vietnam Airlines" },
    { code: "VS", name: "Virgin Atlantic" },
    { code: "WS", name: "WestJet" },
    { code: "MF", name: "Xiamen Airlines" },
    { code: "AM", name: "Aeromexico" },
  ],
};

export const uniqueAirlines = [
  { code: "TN", name: "Air Tahiti Nui" },
  { code: "AS", name: "Alaska Airlines" },
  { code: "AA", name: "American Airlines" },
  { code: "AAA", name: "American AAdvantage" },
  { code: "DLS", name: "Delta SkyMiles" },
  { code: "AMP", name: "Alaska Milage Plan" },
  { code: "9K", name: "Cape Air" },
  { code: "CX", name: "Cathay Pacific" },
  { code: "EY", name: "Etihad Airways" },
  { code: "FJ", name: "Fiji Airways" },
  { code: "AY", name: "Finnair" },
  { code: "G3", name: "GOL Airlines" },
  { code: "HA", name: "Hawaiian Airlines" },
  { code: "IB", name: "Iberia" },
  { code: "JL", name: "Japan Airlines" },
  { code: "B6", name: "JetBlue Airways" },
  { code: "MH", name: "Malaysia Airlines" },
  { code: "QF", name: "Qantas Airways" },
  { code: "QR", name: "Qatar Airways" },
  { code: "AT", name: "Royal Air Maroc" },
  { code: "RJ", name: "Royal Jordanian" },
  { code: "AZ", name: "ITA Airways" },
  { code: "UL", name: "SriLankan Airlines" },
  { code: "BA", name: "British Airways" },
  { code: "EI", name: "Aer Lingus" },
  { code: "DE", name: "Condor" },
  { code: "LY", name: "EL AL Israel Airlines" },
  { code: "HU", name: "Hainan Airlines" },
  { code: "FI", name: "Icelandair" },
  { code: "KE", name: "Korean Air" },
  { code: "LA", name: "LATAM Airlines" },
  { code: "7H", name: "Ravn Alaska" },
  { code: "SQ", name: "Singapore Airlines" },
  { code: "JX", name: "STARLUX Airlines" },
  { code: "DL", name: "Delta Airlines" },
  { code: "AR", name: "Aerolineas Argentinas" },
  { code: "AF", name: "Air France" },
  { code: "MU", name: "China Eastern Airlines" },
  { code: "CI", name: "China Airlines" },
  { code: "CZ", name: "China Southern Airlines" },
  { code: "GA", name: "Garuda Indonesia" },
  { code: "KL", name: "KLM Royal Dutch Airlines" },
  { code: "AE", name: "Mandarin Airlines" },
  { code: "ME", name: "Middle East Airlines" },
  { code: "SV", name: "Saudia Airlines" },
  { code: "FM", name: "Shanghai Airlines" },
  { code: "RO", name: "Tarom" },
  { code: "VN", name: "Vietnam Airlines" },
  { code: "VS", name: "Virgin Atlantic" },
  { code: "WS", name: "WestJet" },
  { code: "MF", name: "Xiamen Airlines" },
  { code: "AM", name: "Aeromexico" },
];

export const US_AVOID_CONNECTIONS = [
  "ATL",
  "BOS",
  "BWI",
  "CLT",
  "DEN",
  "DFW",
  "DTW",
  "EWR",
  "FLL",
  "HNL",
  "IAD",
  "IAH",
  "JFK",
  "LAS",
  "LAX",
  "LGA",
  "MCO",
  "MIA",
  "MSP",
  "NYC",
  "ORD",
  "PDX",
  "PHL",
  "PHX",
  "SAN",
  "SEA",
  "SFO",
  "SLC",
  "SMF",
  "STL",
  "TPA",
];

export default airlines;
